### ISSUE TITLE
Progress Bar Optimierungen

### ISSUE THREAD

**Issue by PhilippHunter** [PhilippHunter/agile-swe-reifegradmodell#12]
- Labels über Bullet Points zentrieren
- Aktuelles Label fett drucken
- Balken/Linie der Progressbar prozentual füllen

**Comment by CodeTriager** [comment]
wenn man die Breite des Fenster klein macht, wird die Progress Bar gespalten, weil ein Textfeld zwei Zeilen dann braucht

**Comment by PhilippHunter** [comment]
gefixt, indem Titel bei kleinen Screens wegfallen.

**Comment by PhilippHunter** [comment]
gefixt, indem Titel bei kleinen Screens wegfallen.
