### ISSUE TITLE
Fragen in Frageform bringen

### ISSUE THREAD

**Issue by PhilippHunter** [PhilippHunter/agile-swe-reifegradmodell#2]
Fragetitel als ganzer Satz mit Fragezeichen.
Antwortmöglichkeiten als ganzer Satz.

**Comment by PhilippHunter** [comment]
"processes"-Teil ist geupdated.

**Comment by vedatbotuk** [comment]
```skills_culture``` and ```strategy``` wurde angepasst.

**Comment by vedatbotuk** [comment]
Alle fragen angepasst.
