### ISSUE TITLE
Results page

### ISSUE THREAD

**Issue by PhilippHunter** [PhilippHunter/agile-swe-reifegradmodell#3]
- Radarchart
- "Geschafft"-Nachricht
- PDF drucken
- Verbesserungsvorschäge

mögliche Zusatzfeatures:
- Gewichtung der Fragen hier anzeigen

**Comment by CodeTriager** [comment]
Radarchart und grundlegendes Konzept wurden eingebaut. 

- PDF drucken fehlt noch 

- Verbesserungsvorschläge müssen noch definiert werden

**Comment by PhilippHunter** [comment]
Verbesserungsvorschläge:
- keine spezifischen Vorschläge zur Verbesserung

- Anzeigen aller Antworten im Kompaktformat (evtl. Kurztitel für Fragen definieren + Farbiger Score [rot, gelb, grün für score])
- Gruppierung nach Dimension (Anzeige in verschiedenen Tabs/Collapsibles...)
- Weitere Gruppierung nach Score der Antwort ("viel Verbesserungspotential", "mittleres Verbess..", "kaum Verbesse...")

**Comment by CodeTriager** [comment]
- Gesamtscore einbauen (prozentual
- Menü von Graphen entfernen
