### ISSUE TITLE
Homepage styling anpassen

### ISSUE THREAD

**Issue by PhilippHunter** [PhilippHunter/agile-swe-reifegradmodell#4]
- "zu den Fragen" Btn in Hero section
- Testimonials styling anpassen (evtl. Slider)

**Comment by PhilippHunter** [comment]
Inhalte zu "Schnell und Einfach":
- einfacher Fragebogen
- ohne Anmeldung
- wenige Minuten
- paar Klicks
- mit Smartphone ausfüllbar

**Comment by PhilippHunter** [comment]
Inhalte zu "Individuelle Schwerpunkte":
- Bewertung je nach eigenem Schwerpunkt
- Schwerpunkt selbst definierbar

**Comment by PhilippHunter** [comment]
Inhalte zu "Übersichtliche Ergebnisse":
- Ergebnisse übersichtlich dargestellt (Netzgraph)
- Individuelles Feedback (je nach Ergebnis)
- Export der Ergebnisse möglich

**Comment by PhilippHunter** [comment]
Inhalte zu "In Zusammenarbeit mit Experten":
- nach wissenschaftlicher Recherche
- Kontakt zu Experten
- Validierung der Inhalte

**Comment by JanDistler** [comment]
Die Inhalte sind nun im develop branch

**Comment by JanDistler** [comment]
Ich habe auch farbliche Anpassungen an der Homepage vorgenommen

**Comment by JanDistler** [comment]
Experten hinzufügen

**Comment by JanDistler** [comment]
Experten wurden hinzugefügt...
Keine weiteren Änderungen geplant --> Closed
