### ISSUE TITLE
Umfrage / Fragen-Komponente

### ISSUE THREAD

**Issue by PhilippHunter** [PhilippHunter/agile-swe-reifegradmodell#7]
- Scoring (Ergebnisse speichern und gewichten)
- Durchklick-Mechanismus
- Fortschrittsanzeige

**Comment by CodeTriager** [comment]
Fortschrittsanzeige wurde grundlegend eingebaut. CSS Verbesserungen sind hier noch zu erledigen.

**Comment by PhilippHunter** [comment]
Idee für Fragenbewertung:
- Nutzer bestimmt zu jeder Dimension genauen Multiplikator (per Slider?)
- So wird jeder Antwortwert aus der Dim multipliziert und gewichtet

**Comment by PhilippHunter** [comment]
ConfirmDialog verwenden, wenn von ausgefüllter Umfrage wegnavigiert wird.

**Comment by PhilippHunter** [comment]
Initiales System für die Speicherung der User-Choices eingebaut. Index der Choice wird nun am Fragenobjekt als weiterer Wert gespeichert und nicht direkt der Score.
